### ISSUE TITLE
Connect over SSL

### ISSUE THREAD

**Issue by wojtek-oledzki** [streamthoughts/kafka-specs#14]
This might be naive question, but how can I connect to my Kafka cluster over SSL. Admin Config does not support ssl.* options :(

```
WARN  o.a.k.c.admin.AdminClientConfig - The configuration 'ssl.truststore.location' was supplied but isn't a known config.
WARN  o.a.k.c.admin.AdminClientConfig - The configuration 'ssl.keystore.password' was supplied but isn't a known config.
WARN  o.a.k.c.admin.AdminClientConfig - The configuration 'ssl.key.password' was supplied but isn't a known config.
WARN  o.a.k.c.admin.AdminClientConfig - The configuration 'ssl.keystore.location' was supplied but isn't a known config.
WARN  o.a.k.c.admin.AdminClientConfig - The configuration 'ssl.truststore.password' was supplied but isn't a known config.
```

**Comment by fhussonnois** [comment]
Hi @wojtek-oledzki, I think you have missed to configure the property `security.protocol`

You can passed this property to kafka-specs command line with `--command-property security.protocol="SSL`

**Comment by wojtek-oledzki** [comment]
I will re-test today using `--command-property` instead of properties files.

**Comment by fhussonnois** [comment]
@wojtek-oledzki you can still use the properties files. It seems that AdminClientConfig dosen't recognize ssl.* properties if you don't configure the security.protocol. So you can also add thise property to your config file.

**Comment by wojtek-oledzki** [comment]
not sure how I've missed that 😊 
Thanks

```
security.protocol=SSL
ssl.key.password=...
ssl.keystore.location=/secrets/kafka-specs.keystore.jks
ssl.keystore.password=...
ssl.truststore.location=/secrets/kafka-specs.truststore.jks
ssl.truststore.password=...
client.id=kafka-specs
```
